---
- hosts: mynodes
  gather_facts: no
  become: true
  tasks:
  - name: Ensure latest version of Python installed
    raw: apk -U add python3
  - name: Ensure latest version of Apache installed
    apk:
       name: apache2
       state: latest
  - name: Copy index.html into place
    template:
       src: index.html
       dest: /var/www/localhost/htdocs/index.html
    notify:
    - restart apache
  - name: Ensure Apache is running
    service:
      name: apache2
      state: started
  handlers:
    - name: restart apache
      service:
         name: apache2
         state: restarted
